# permissions for end users to view hoges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hoge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: example-controller
    app.kubernetes.io/part-of: example-controller
    app.kubernetes.io/managed-by: kustomize
  name: hoge-viewer-role
rules:
- apiGroups:
  - example.sosomasox.com
  resources:
  - hoges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.sosomasox.com
  resources:
  - hoges/status
  verbs:
  - get
